# Generated by Django 3.2.8 on 2021-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(max_length=9),
        ),
    ]
