# Generated by Django 3.2.8 on 2021-11-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizew', '0002_alter_syllabus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='assignments',
            field=models.TextField(default='Be the best you you can be'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='attendance_rule',
            field=models.TextField(default='Stick around!'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='class_preparation',
            field=models.TextField(default='Listen, learn, grow'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(default="A course that didn't have one!"),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_objectives',
            field=models.TextField(default='Just try your hardest!'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_requirements',
            field=models.TextField(default='See class preparation steps'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_site',
            field=models.TextField(default='https://blackboard.umbc.edu'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_time',
            field=models.TextField(default='9am-5pm'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='exams',
            field=models.TextField(default='Those really tough days and situations'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='grade_breakdown',
            field=models.TextField(default='If you try, you get 100%'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='hands_on',
            field=models.TextField(default='See participation grade'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='homework',
            field=models.TextField(default='Life has no homework (wish school was the same)'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instruct_methods',
            field=models.TextField(default='IRL talking'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor_email',
            field=models.CharField(default='noreply@umbc.edu', max_length=41),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor_name',
            field=models.TextField(default='Dr. Hrabowski'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor_phone',
            field=models.CharField(default='(410) 455-1000', max_length=14),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='late_policy',
            field=models.TextField(default='Whenever it suits you'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='makeup_policy',
            field=models.TextField(default='There are no second chances'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='office_hours',
            field=models.TextField(default='2-3am'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='participation',
            field=models.TextField(default='100% of your grade is being there'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='prereqs',
            field=models.TextField(default='Admission to UMBC, a willingness to succeed, and a passion for more'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='prog_assignments',
            field=models.TextField(default='Arguments and confrontations'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='quizzes',
            field=models.TextField(default="Also called 'bad news'"),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_file',
            field=models.FileField(default='syllabus.pdf', upload_to='syllabi/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='ta_email',
            field=models.CharField(default='UMBCHelp@rt.umbc.edu', max_length=41),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='ta_name',
            field=models.TextField(default='Philip Rous'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='textbook',
            field=models.TextField(default='Dune by Frank Herbert'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(default='TUFF 101', max_length=9),
        ),
    ]
