# Generated by Django 3.2.8 on 2021-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizew', '0003_auto_20211101_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='id',
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(default='TUFF 101', max_length=9, primary_key=True, serialize=False),
        ),
    ]
