# Generated by Django 3.2.8 on 2021-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
