# Generated by Django 3.2.9 on 2021-12-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20211122_1631'),
        ('login', '0009_auto_20211126_1934'),
    ]

    operations = [
    ]
