# Generated by Django 3.2.9 on 2021-12-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_merge_0009_auto_20211122_1631_0009_auto_20211126_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('dept', 'Department')], default='student', max_length=10),
        ),
    ]
