# Generated by Django 3.2.8 on 2021-11-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabi',
            fields=[
                ('semester_held', models.CharField(max_length=200)),
                ('semester_year', models.IntegerField()),
                ('class_dept', models.CharField(max_length=4)),
                ('class_code', models.IntegerField()),
                ('class_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.syllabi')),
            ],
        ),
        migrations.AddField(
            model_name='syllabi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
