# Generated by Django 3.2.8 on 2021-11-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211111_1347'),
        ('backend', '0002_auto_20211113_1927'),
    ]

    operations = [
    ]
