# Generated by Django 3.2.5 on 2021-11-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_form', '0002_item_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
