# Generated by Django 3.2.5 on 2021-11-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus_form', '0003_auto_20211102_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
