# Generated by Django 3.2.5 on 2021-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_form', '0005_auto_20211102_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='className',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
