# Generated by Django 3.2.5 on 2021-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_form', '0006_auto_20211102_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='className',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(max_length=100),
        ),
    ]
