# Generated by Django 3.2.8 on 2021-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('office_phone', models.CharField(max_length=20)),
                ('office_hours', models.CharField(max_length=200)),
            ],
        ),
    ]
