# Generated by Django 3.2.8 on 2021-12-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('faculty_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.CharField(default='None', max_length=100)),
                ('phone', models.CharField(default='+1 (000) 000-0000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_profile.profile')),
            ],
            options={
                'ordering': ['faculty_id'],
            },
        ),
    ]
