# Generated by Django 3.2.8 on 2021-12-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.CharField(default='None', max_length=100)),
                ('phone', models.CharField(default='+1 (000) 000-0000', max_length=20)),
            ],
        ),
    ]
