# Generated by Django 3.2.8 on 2021-11-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
